version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Pic.me-server
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/run-after-deploy.sh
      runas: ubuntu
