version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/Pic.me-server
      overwrite: yes
permissions:
    - object: /home/ubuntu
      pattern: "**"
      owner: ubuntu
      group: ubuntu
hooks:
    BeforeInstall:
        - location: scripts/delete-before-process.sh
          timeout: 300
          runas: ubuntu
    AfterInstall:
        - location: scripts/run-after-install.sh
          timeout: 300
          runas: ubuntu
