version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/Pic.me-server
permissions:
    - object: /home/ubuntu/Pic.me-server
      owner: ubuntu
    - object: /home/ubuntu/Pic.me-server/*/**
      owner: ubuntu
hooks:
    BeforeInstall:
        - location: scripts/delete-before-process.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/run-after-install.sh
          timeout: 300
          runas: root
